spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydatabase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: false # Spring Boot 3.1+ 의 Docker Compose 자동 연동 기능을 끄고, 띄워져 있는 컨테이너만 사용할 때 활성화

  batch:
    jdbc:
      initialize-schema: always # Spring Batch가 실행에 필요한 메타 데이터 테이블(ex. BATCH_JOB_EXECUTION 등)을 DB에 자동 생성할지 여부. always는 매번 앱 기동 시 스크립트를 실행하여 생성 시도
    job:
      enabled: false            # 애플리케이션 시작 시점에 ApplicationContext 안에 등록된 Batch Job 빈들을 자동으로 전부 실행시킬지 여부. false로 하면 API나 스케줄러를 통해서만 Job을 수동 실행 가능

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090 # 사용중인 포트(8080)와 충돌이 날 경우 이 값을 8090 등으로 변경하세요
